combined:
	g++ -o combined combined.cpp ../general/gfft_parallel.cpp ../general/gfft.cpp ../general/gfft_inplace.cpp ../utils.cpp `pkg-config --cflags --libs opencv4` -lsfml-graphics -lsfml-window -lsfml-system

twocoords:
	g++ -o twocoords two_coords.cpp ../general/gfft_parallel.cpp ../general/gfft.cpp ../general/gfft_inplace.cpp ../utils.cpp `pkg-config --cflags --libs opencv4` -lsfml-graphics -lsfml-window -lsfml-system

combined_parallel:
	g++ -o combined_parallel combined_parallel.cpp ../general/gfft_parallel.cpp ../general/gfft.cpp ../general/gfft_inplace.cpp ../utils.cpp `pkg-config --cflags --libs opencv4` -lsfml-graphics -lsfml-window -lsfml-system

twocoords_parallel:
	g++ -o two_coords_parallel two_coords_parallel.cpp ../general/gfft_parallel.cpp ../general/gfft.cpp ../general/gfft_inplace.cpp ../utils.cpp `pkg-config --cflags --libs opencv4` -lsfml-graphics -lsfml-window -lsfml-system

drawing:
	g++ -o drawing drawing.cpp ../general/gfft_parallel.cpp ../general/gfft.cpp ../general/gfft_inplace.cpp ../utils.cpp `pkg-config --cflags --libs opencv4` -lsfml-graphics -lsfml-window -lsfml-system
